config/routes.rb
BeatsRealmApp::Application.routes.draw do
  get "artist_bios/edit"
  root "static_pages#home"
  get 'faq' => 'static_pages#faq'
  get 'contact' => 'static_pages#contact'
  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'copyright_info' => 'static_pages#copyright_info'
  get 'artist_signup' => 'artists#new'
  get 'login' => 'artist_sessions#new'
  delete 'logout' => 'artist_sessions#destroy'
  get 'discover' => 'artists#index'
  resources :artists do
    get 'create_bio'
    get 'edit_bio'
    get 'bio'
  end
  resources :artist_bios, only: [:edit, :update]
  resources :artist_sessions, only: [:new, :create, :destroy]
  resources :artist_account_activations, only: [:edit]
  resources :artist_password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]

end

app/controllers/artist_sessions_controller.rb
class ArtistSessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to current_artist
    else
      render 'new'
    end
  end

  def create
    artist = Artist.find_by(email: params[:session][:email].downcase)
    if artist && artist.authenticate(params[:session][:password])
      if artist.activated?
        log_in artist
        params[:session][:remember_me] == '1' ? remember(artist) : forget(artist)
        redirect_back_or artist
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    forget(current_artist)
    session.delete(:artist_id)
    @current_artist = nil
    redirect_to root_url
  end
end

app/views/artist_sessions/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: artist_sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= link_to "(forgot password)", new_artist_password_reset_path %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
      <%= f.check_box :remember_me %>
      <span>Remember me on this computer</span>
      <% end %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>Want your own artist page? <%= link_to "Sign up now!", artist_signup_path %></p>
  </div>
</div>