config/routes.rb
BeatsRealmApp::Application.routes.draw do
  get "artist_bios/edit"
  root "static_pages#home"
  get 'faq' => 'static_pages#faq'
  get 'contact' => 'static_pages#contact'
  get 'privacy_policy' => 'static_pages#privacy_policy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'copyright_info' => 'static_pages#copyright_info'
  get 'artist_signup' => 'artists#new'
  get 'login' => 'artist_sessions#new'
  delete 'logout' => 'artist_sessions#destroy'
  get 'discover' => 'artists#index'
  resources :artists do
    get 'create_bio'
    get 'edit_bio'
    get 'bio'
  end
  resources :artist_bios, only: [:edit, :update]
  resources :artist_sessions, only: [:new, :create, :destroy]
  resources :artist_account_activations, only: [:edit]
  resources :artist_password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "FAQ",   faq_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Privacy Policy", privacy_policy_path %></li>
      <li><%= link_to "Terms of Service", terms_of_service_path %></li>
      <li><%= link_to "Copyright Info", copyright_info_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Beats Realm", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "discover", discover_path %></li>
        <% if logged_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= "#{current_artist.artist_name}" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "profile", current_artist %></li>
              <li><%= link_to "settings", edit_artist_path(current_artist) %></li>
              <li><%= link_to "log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "artist signup", artist_signup_path %></li>
          <li><%= link_to "log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>